name: CI/CD

on:
  push:
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm run lint
  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Publish package to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build package to upload to GitHub releases
        run: |
          npm pack
          mv acpr-rate-limit-postgresql-*.tgz acpr-rate-limit-postgresql.tgz
      - name: Create a Github release
        uses: softprops/action-gh-release@v1
        with:
          files: acpr-rate-limit-postgresql.tgz
          body:
            You can view the changelog
            [here](https://github.com/adrianprelipcean/express-rate-limit-postgresql/blob/master/changelog.md).